language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  allow_failures:
    - php: 7.0
    - php: 7.1
    - php: hhvm

before_script:
  - composer install

script: vendor/bin/phpunit

after_script:
  - vendor/bin/coveralls -v
